Задача 1. Инициализация рабочего окружения
ndreuu/formal-lang-course pull request #1
Opened 2022-09-11 18:21 UTC by ndreuu

Реализовал модуль, предоставляющий возможности, описанные в задаче 1

2022-09-14 08:20 UTC, vadyushkins requested changes

2022-09-14 08:20 UTC, vadyushkins commented on .github/workflows/tests.yml
> +    runs-on: ubuntu-latest
Добавьте windows, macos

2022-09-14 08:20 UTC, vadyushkins commented on project/graph_info.py
> +    n_edges: int
Непонятно что значит `n_nodes`, `n_edges`. Сделайте читаемые имена. Например `nodes_num` или `number_of_nodes`.

2022-09-14 08:20 UTC, vadyushkins commented on project/utilities.py
> +def generate_two_cycles_graph(n, m, labels, path):
`n, m, labels, path` -- сделайте более читабельные имена аргументов

2022-09-14 08:20 UTC, vadyushkins commented on tests/test_task1/test_task1.py
> +    # from: https: // jetbrains - research.github.io / CFPQ_Data / dataset / index.html
?

2022-09-14 08:20 UTC, vadyushkins commented on tests/test_task1/test_task1.py
> +    info = get_graph_info("skos")
Добавьте больше графов. Изучите крайние случаи.

2022-09-14 08:20 UTC, vadyushkins commented on tests/test_task1/test_task1.py
> +    generate_two_cycles_graph(3, 2, ["a", "b"], "tests/test_task1/generated_graph.dot")
Добавьте больше графов. Изучите крайние случаи.

2022-09-14 08:20 UTC, vadyushkins commented on tests/test_task1/test_task1.py
> +    os.remove("tests/test_task1/generated_graph.dot")
Используйте pytest tmp_path

2022-09-14 20:33 UTC, ndreuu commented on .github/workflows/tests.yml
> +    runs-on: ubuntu-latest
done

2022-09-14 20:33 UTC, ndreuu commented on project/graph_info.py
> +    n_edges: int
done

2022-09-14 20:33 UTC, ndreuu commented on project/utilities.py
> +def generate_two_cycles_graph(n, m, labels, path):
done

2022-09-14 20:33 UTC, ndreuu commented on tests/test_task1/test_task1.py
> +    info = get_graph_info("skos")
done

2022-09-14 20:33 UTC, ndreuu commented on tests/test_task1/test_task1.py
> +    generate_two_cycles_graph(3, 2, ["a", "b"], "tests/test_task1/generated_graph.dot")
done

2022-09-14 20:33 UTC, ndreuu commented on tests/test_task1/test_task1.py
> +    os.remove("tests/test_task1/generated_graph.dot")
done

2022-09-14 20:34 UTC, ndreuu commented on tests/test_task1/test_task1.py
> +    # from: https: // jetbrains - research.github.io / CFPQ_Data / dataset / index.html
это для себя, забыл удалить (done)

2022-09-15 10:12 UTC, vadyushkins approved these changes
зачтено

2022-09-18 09:00 UTC, merged