task3
ndreuu/formal-lang-course pull request #3
Opened 2022-09-25 20:28 UTC by ndreuu

- [X] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
- [X] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [X] Добавить необходимые тесты.

2022-09-26 18:16 UTC, vadyushkins requested changes
1. Не вижу у вас функции пересечения двух конечных автоматов
2. Вынесите данные для тестов в отдельные JSON файлы (по одному файлы с набором данных на одну функцию\метод). Напишите фикстуру загрузки этих данных

2022-09-26 18:16 UTC, vadyushkins commented on project/boolean_decompositon.py
> +from pyformlang.finite_automaton import NondeterministicFiniteAutomaton, State
```suggestion
import scipy
import pyformlang
```

2022-09-28 23:33 UTC, ndreuu commented
> 1. Не вижу у вас функции пересечения двух конечных автоматов
> 
>     2. Вынесите данные для тестов в отдельные JSON файлы (по одному файлы с набором данных на одну функцию\метод). Напишите фикстуру загрузки этих данных

1 -- вынес в отдельный файл тесты
2 -- сделал для rpq

2022-09-28 23:43 UTC, ndreuu commented
тест из первого задания закоменчен, потому что не работает библиотечная функция

2022-09-30 09:50 UTC, vadyushkins requested changes
замечания надо поправить
еще что-то не вижу, чтобы у BooleanDecomposition все публичные функции были протестированы
может это верно не только для BooleanDecomposition, посмотрите

2022-09-30 09:50 UTC, vadyushkins commented on project/boolean_decompositon.py
> +from scipy import sparse
тогда уж оставьте только from scipy import sparse

2022-09-30 09:50 UTC, vadyushkins commented on project/boolean_decompositon.py
> +from pyformlang.finite_automaton import NondeterministicFiniteAutomaton, State
import pyformlang

2022-09-30 09:50 UTC, vadyushkins commented on tests/test_task3/test_intersection.py
> +    assert fa.is_equivalent_to(expected)
Вы кажется не поняли, нужно все данные вынести в json - и данные для сборки теста и expected данные для проверки того, что тест сделал то, что вы тестируете (например собрал автомат который вы собираете)

2022-09-30 09:50 UTC, vadyushkins commented on tests/test_task3/test_rpq.py
> +    return [construct_touple(cur_block) for cur_block in test_datas[test_name]]
touple?

2022-09-30 09:50 UTC, vadyushkins commented on tests/test_task3/test_rpq.py
> +def test_two_cycle_graph(graph, query, start_nodes, final_nodes, expected_rpq):
graph, query, start_nodes, final_nodes, expected_rpq - все должно лежать в json
а вы только подгружаете из него

2022-10-04 05:11 UTC, vadyushkins approved these changes
зачтено

2022-10-04 18:36 UTC, merged